export const RECIVE_TIMETABLE = "RECIVE_TIMETABLE_STUDENT";
export const RECIVE_GRADES = "RECIVE_GRADES_STUDENT";

export const ADD_ERROR = "ADD_ERROR";
export const ADD_MESSAGE = "ADD_MESSAGE_ADMIN";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE_ADMIN";
