export const RECIVE_TIMETABLE = "RECIVE_TIMETABLE_TEACHER";
export const RECIVE_COURSES = "RECIVE_COURSES_TEACHER";
export const RECIVE_GRADES = "RECIVE_GRADES_TEACHER";
export const ADD_GRADE = "ADD_GRADE_TEACHER";
export const EDIT_GRADE = "EDIT_GRADE_TEACHER";
export const DELETE_GRADE = "DELETE_GRADE_TEACHER";

export const ADD_ERROR = "ADD_ERROR";
export const ADD_MESSAGE = "ADD_MESSAGE_ADMIN";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE_ADMIN";
