version: '3.2'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: example
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5431:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080
